version: '3'

tasks:
  default:
    cmds:
      - task --list-all
  rebuild:
    deps:
      - format
    cmds: 
      - nix flake update
      - sudo nix run nix-darwin -- switch --flake .
  format:
    cmds:
      - nixfmt flake.nix
