version: "3"

dotenv:
  - .env.local

tasks:
  default:
    cmds:
      - task --list-all
  rebuild:
    deps:
      - format
    cmds:
      - sudo nix flake update --option access-tokens "github.com=$(gh auth token)"
      - sudo nix run nix-darwin -- switch --flake .
  format:
    cmds:
      - nixfmt flake.nix
  skills:add:anthropics:
    cmds:
      - skills add anthropics/skills
  skills:add:vercel-labs:
    cmds:
      - skills add vercel-labs/agent-skills
  claude:plugin:add:anthropic:
    cmds:
      - claude plugin install -s user Notion@claude-plugins-official
      - claude plugin install -s user claude-code-setup@claude-plugins-official
      - claude plugin install -s user claude-md-management@claude-plugins-official
      - claude plugin install -s user code-review@claude-plugins-official
      - claude plugin install -s user code-simplifier@claude-plugins-official
      - claude plugin install -s user frontend-design@claude-plugins-official
      - claude plugin install -s user github@claude-plugins-official
      - claude plugin install -s user hookify@claude-plugins-official
      - claude plugin install -s user plugin-dev@claude-plugins-official
      - claude plugin install -s user pr-review-toolkit@claude-plugins-official
      - claude plugin install -s user security-guidance@claude-plugins-official
  claude:plugin:add:superpowers:
    cmds:
      - claude plugin marketplace add obra/superpowers-marketplace
      - claude plugin install -s user superpowers@superpowers-marketplace
  claude:plugin:add:lsp-servers:
    cmds:
      - claude plugin marketplace add yungweng/claude-lsp-servers
      - claude plugin install -s user lsp-servers@claude-lsp-servers
