version: '3'

tasks:
  default:
    cmds:
      - task --list-all

  lang:fix:
    cmds:
      - LANG=C xdg-user-dirs-update --force

  format:
    cmds:
      - nixfmt *.nix

  init:
    cmds:
      - |
        sudo nixos-rebuild switch \
        --flake .#nixos
        --option extra-substituters https://install.determinate.systems \
        --option extra-trusted-public-keys cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM= \

  rebuild:
    deps:
      - format
    cmds:
      - sudo nix flake update
      - sudo nixos-rebuild switch --flake .#nixos
